# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "CI_Pipeline_Enablement" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest # GitHub-hosted runner

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      # Uses the allowed SSH action for deployment
      #- name: Deploying to Linux Machine
      #  uses: actions-ext/appleboy-ssh-action@v1
      #  with:
      #    host: ${{ secrets.SERVER_IP }} # IP of your remote server
      #    username: ${{ secrets.SERVER_USER }} # SSH username for the remote server
      #    key: ${{ secrets.SERVER_KEY }} # SSH private key for authentication
      #   port: ${{ secrets.SERVER_PORT }} # SSH port of the remote server
      #    timeout: 300s
      #    script: |
      #     echo "Running deployment script on remote server"
            # Add your actual deployment commands here

      # Runs a single command using the runner's shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs build commands in the specified shell
      #- name: Run Build
      #  run: |
      #    source settings.csh
      #    make clean build sim TXN=1
      #  shell: bash
